package com.jobportal.utility;

public class Data {
	public static String getMessageBody(String otp) {
		return "<!DOCTYPE html>\r\n"
				+ "<html>\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>OTP Verification</title>\r\n"
				+ "    <style>\r\n"
				+ "        body {\r\n"
				+ "            font-family: Arial, sans-serif;\r\n"
				+ "            background-color: #f4f4f4;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            text-align: center;\r\n"
				+ "        }\r\n"
				+ "        .email-container {\r\n"
				+ "            max-width: 500px;\r\n"
				+ "            margin: auto;\r\n"
				+ "            background: #ffffff;\r\n"
				+ "            padding: 20px;\r\n"
				+ "            border-radius: 8px;\r\n"
				+ "            box-shadow: 0px 0px 10px rgba(0, 0, 0, 0.1);\r\n"
				+ "        }\r\n"
				+ "        .otp-code {\r\n"
				+ "            font-size: 24px;\r\n"
				+ "            font-weight: bold;\r\n"
				+ "            color: #333;\r\n"
				+ "            margin: 20px 0;\r\n"
				+ "        }\r\n"
				+ "        .footer {\r\n"
				+ "            font-size: 12px;\r\n"
				+ "            color: #777;\r\n"
				+ "            margin-top: 20px;\r\n"
				+ "        }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <div class=\"email-container\">\r\n"
				+ "        <h2>OTP Verification</h2>\r\n"
				+ "        <p>Your One-Time Password (OTP) for verification is:</p>\r\n"
				+ "        <p class=\"otp-code\">"+otp+"</p>\r\n"
				+ "        <p>Please use this OTP to complete your verification. Do not share this OTP with anyone.</p>\r\n"
				+ "        <p class=\"footer\">If you did not request this, please ignore this email.</p>\r\n"
				+ "    </div>\r\n"
				+ "</body>\r\n"
				+ "</html>\r\n";
	}
}
